import type { Capability } from "./types";

export const categoryLabels: Record<string, string> = {
  "AI Workflow": "AI 工作流",
  "Chat UI": "聊天界面",
  "Game UI": "游戏界面",
  "Image & Media": "图片与媒体",
  "Image & Vision": "图片与视觉",
  "Map & Data": "地图与数据",
  "Motion & Animation": "动效与动画",
  Prompt: "提示词",
  "UI Interaction": "界面交互",
  "Visual Effects": "视觉效果",
};

export const difficultyLabels: Record<Capability["difficulty"], string> = {
  advanced: "较难",
  easy: "简单",
  medium: "中等",
};

export const modeLabels: Record<Capability["mode"], string> = {
  ai_native: "AI 原生",
  frontend: "前端能力",
  interaction: "交互效果",
  visual: "视觉效果",
};

export function getCategoryLabel(category: string) {
  return categoryLabels[category] ?? category;
}

const commonAssets = (ready: string[] = []): Capability["packageAssets"] => {
  const assets = [
    ["Self-owned source", "自研源码"],
    ["Cursor Prompt", "Cursor 提示词"],
    ["Claude Prompt", "Claude 提示词"],
    ["README", "使用说明"],
    ["Parameters", "参数说明"],
    ["Integration Guide", "接入指南"],
    ["License", "许可证"],
  ] as const;
  return assets.map(([key, label]) => ({
    label,
    status: ready.includes(key) ? "ready" : "planned",
    note: ready.includes(key) ? "已在本地预览中验证" : "尚未作为公开 Package 交付",
  }));
};

export const capabilities: Capability[] = [
  {
    category: "Image & Vision",
    categoryZh: "图片与视觉",
    description: "从图片提取主色、辅助色和可复用的调色板结果。",
    displayNameZh: "图片取色",
    difficulty: "medium",
    id: "image-color-extractor",
    mode: "ai_native",
    name: "Color Extraction",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "图片里的颜色很难快速转成可用于 UI、海报或主题系统的结构化数据。",
    previewStatus: "preview_ready",
    slug: "color-extraction",
    sourceStatus: "self_owned_prototype",
    stack: ["Canvas", "React", "TypeScript"],
    summary: "把图片转换成可以直接使用的配色方案。",
    tags: ["Color Picker", "Palette", "Vision", "Image"],
    useCases: ["主题色生成", "图片分析", "视觉灵感板", "分享海报"],
  },
  {
    category: "Visual Effects",
    categoryZh: "视觉效果",
    description: "可复用的玻璃拟态卡片，支持模糊、透明度、边框、高光和鼠标交互。",
    displayNameZh: "玻璃拟态卡片",
    difficulty: "easy",
    id: "glass-surface",
    mode: "visual",
    name: "Glass Surface",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "玻璃拟态容易停留在视觉模仿，难以形成可复用的参数和接入方式。",
    previewStatus: "preview_ready",
    slug: "glass-surface",
    sourceStatus: "self_owned_prototype",
    stack: ["CSS", "React", "Tailwind"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 1, subtitleZh: "拆解 AI 产品里的玻璃拟态卡片" },
    summary: "一张可以直接接入 AI 产品的玻璃拟态卡片。",
    tags: ["Glass", "VisionOS", "Apple", "Surface"],
    useCases: ["AI 数据面板", "首页首屏", "结果卡片", "媒体预览"],
  },
  {
    category: "Chat UI",
    categoryZh: "聊天界面",
    description: "把等待、生成、完成和手动查看组织成一个会自动展开与收起的处理过程面板。",
    difficulty: "medium",
    displayNameZh: "AI 思考过程面板",
    id: "ai-reasoning-panel",
    mode: "ai_native",
    name: "AI Reasoning Panel",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 处理需要等待时，用户很难判断系统是否仍在工作；过程信息长期展开又会挤占最终答案。",
    previewStatus: "preview_ready",
    slug: "ai-reasoning-panel",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Disclosure", "ARIA Live Regions"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 16, subtitleZh: "AI 回复前的几秒，界面应该怎么设计" },
    summary: "一个尊重用户控制、只展示公开处理摘要的 AI 状态面板。",
    tags: ["Reasoning", "AI Status", "Streaming", "Disclosure", "Chat UI"],
    useCases: ["AI 对话", "Agent 执行", "文档分析", "内容生成"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "在 AI 执行删除、发送或发布等敏感操作前，清楚展示动作、对象和风险，并让用户明确允许或拒绝。",
    difficulty: "medium",
    displayNameZh: "AI 操作授权确认卡",
    id: "ai-action-approval-card",
    mode: "ai_native",
    name: "AI Action Approval Card",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 自动执行敏感操作时，如果用户看不见动作范围、影响对象和拒绝路径，就很难建立信任。",
    previewStatus: "preview_ready",
    slug: "ai-action-approval-card",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Controlled State", "ARIA Live Regions"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 17, subtitleZh: "AI 真正执行前，为什么要先问你一次" },
    summary: "一个把请求、决定、执行和结果留在原位置的 AI 授权交互。",
    tags: ["Approval", "Agent", "Permission", "Safety", "AI Workflow"],
    useCases: ["AI 工作台", "Agent 执行", "文件操作", "发布流程"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "把多个 AI 任务的运行状态、待处理原因、最近进度和下一步动作集中到一个可筛选的收件箱。",
    difficulty: "medium",
    displayNameZh: "AI Agent 任务收件箱",
    id: "agent-task-inbox",
    mode: "ai_native",
    name: "Agent Task Inbox",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "多个 Agent 并行工作时，运行状态、确认请求和审查结果散落在不同对话里，用户很容易错过真正需要介入的节点。",
    previewStatus: "preview_ready",
    slug: "agent-task-inbox",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Controlled Data", "ARIA Live Regions"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 18, subtitleZh: "多个 AI 同时工作，怎样不漏掉需要你处理的任务" },
    summary: "一个把需要处理、运行中、等待审查和已完成任务集中管理的 AI 工作台模块。",
    tags: ["Agent", "Inbox", "Task", "Status", "AI Workflow"],
    useCases: ["AI 工作台", "AI IDE", "Agent 管理", "长任务执行"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "把答案中的结论与具体来源绑定，点击编号即可查看标题、域名和对应摘录。",
    difficulty: "medium",
    displayNameZh: "AI 引用来源卡片",
    id: "source-citation-preview",
    mode: "ai_native",
    name: "Source Citation Preview",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 给出结论后，用户往往不知道每句话来自哪里，也无法快速核查来源是否真的支持当前结论。",
    previewStatus: "preview_ready",
    slug: "source-citation-preview",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Controlled State", "Accessible Popover"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 19, subtitleZh: "让每条结论都能回到具体来源" },
    summary: "一个为 AI 答案补充行内编号和可核查来源预览的交互模块。",
    tags: ["Citation", "Source", "Research", "AI Chat", "Popover"],
    useCases: ["AI 搜索", "深度研究", "知识问答", "研究助手"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "左侧保留对话上下文，右侧持续展示可编辑成果，并支持版本切换。",
    difficulty: "medium",
    displayNameZh: "AI 成果双栏预览",
    id: "artifact-split-preview",
    mode: "ai_native",
    name: "Artifact Split Preview",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "长内容生成时，对话和最终成果混在同一条消息流中，修改、比较和继续迭代都很费力。",
    previewStatus: "preview_ready",
    slug: "artifact-split-preview",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Responsive Split View", "Version State"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 20, subtitleZh: "让对话与生成成果同时可见" },
    summary: "一个把对话过程和生成成果分栏展示的 AI 工作区模块。",
    tags: ["Artifact", "Split View", "Preview", "Version", "Workspace"],
    useCases: ["AI 写作", "AI 编程", "文档生成", "网页生成"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "展示工具名称、调用目的、运行状态、输入摘要、结果和失败重试。",
    difficulty: "medium",
    displayNameZh: "AI 工具调用状态卡",
    id: "tool-call-activity-card",
    mode: "ai_native",
    name: "Tool Call Activity Card",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 调用搜索、代码或数据工具时，如果只显示等待动画，用户无法判断它正在做什么、是否失败以及下一步该怎么办。",
    previewStatus: "preview_ready",
    slug: "tool-call-activity-card",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Status State", "Progress"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 21, subtitleZh: "把 AI 正在调用的工具说清楚" },
    summary: "一个完整展示 AI 工具调用过程与结果状态的活动卡片。",
    tags: ["Tool Call", "Status", "Agent", "Progress", "Retry"],
    useCases: ["AI Agent", "AI 搜索", "AI 工作台", "自动化任务"],
  },
  {
    category: "Developer Tool",
    categoryZh: "开发者工具",
    description: "按文件组织代码改动，显示增删行、审查进度，并支持逐文件接受或拒绝。",
    difficulty: "advanced",
    displayNameZh: "AI 代码差异审查",
    id: "ai-diff-review",
    mode: "ai_native",
    name: "AI Diff Review",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 一次修改多个文件后，用户很难快速确认改了哪里，也缺少逐文件保留或撤销的明确入口。",
    previewStatus: "preview_ready",
    slug: "ai-diff-review",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Diff Model", "Review State"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 22, subtitleZh: "先看清每一处改动，再决定是否接受" },
    summary: "一个为 AI 代码改动提供文件列表、差异视图和逐项决策的审查模块。",
    tags: ["Diff", "Code Review", "AI IDE", "Developer Tool", "Approval"],
    useCases: ["AI IDE", "代码助手", "自动重构", "生成式开发"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "明确展示 AI 新增了哪些记忆，并允许用户立即修改、删除或切换临时会话。",
    difficulty: "medium",
    displayNameZh: "AI 记忆更新提示",
    id: "memory-update-control",
    mode: "ai_native",
    name: "Memory Update Control",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 记住用户信息时，如果没有即时反馈和控制入口，用户无法判断记住了什么，也不知道如何撤回。",
    previewStatus: "preview_ready",
    slug: "memory-update-control",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Controlled Form", "Privacy State"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 23, subtitleZh: "让用户看见并控制 AI 记住的内容" },
    summary: "一个显示 AI 记忆变化并允许用户编辑、遗忘的控制模块。",
    tags: ["Memory", "Privacy", "AI Chat", "Control", "Preference"],
    useCases: ["AI 助手", "长期对话", "个性化推荐", "客户服务"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "在一次请求中管理图片、音频和文档的上传、解析、排序、失败和重试状态。",
    difficulty: "medium",
    displayNameZh: "多模态附件队列",
    id: "multimodal-attachment-queue",
    mode: "ai_native",
    name: "Multimodal Attachment Queue",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "多个不同类型文件同时进入 AI 请求时，用户很难看清每个文件的处理顺序、当前阶段和失败原因。",
    previewStatus: "preview_ready",
    slug: "multimodal-attachment-queue",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Queue State", "Progress"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 24, subtitleZh: "把图片、音频和文档的处理过程排清楚" },
    summary: "一个统一管理多类型附件上传和解析状态的 AI 输入队列。",
    tags: ["Multimodal", "Upload", "Queue", "Attachment", "AI Input"],
    useCases: ["AI Chat", "会议助手", "文档分析", "图片理解"],
  },
  {
    category: "AI Workflow",
    categoryZh: "AI 工作流",
    description: "把长任务拆成连续步骤，展示当前阶段、完成记录、等待输入和停止入口。",
    difficulty: "medium",
    displayNameZh: "AI 执行时间线",
    id: "agent-execution-timeline",
    mode: "ai_native",
    name: "Agent Execution Timeline",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 长任务只显示一个进度条时，用户不知道完成了什么、正在做什么、卡在哪里，也无法在关键节点介入。",
    previewStatus: "preview_ready",
    slug: "agent-execution-timeline",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Step State", "Accessible Status"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 25, subtitleZh: "把长任务的每一步都变成可检查状态" },
    summary: "一个展示 AI Agent 长任务步骤、状态和人工介入点的时间线模块。",
    tags: ["Agent", "Timeline", "Long Task", "Progress", "Workflow"],
    useCases: ["AI Agent", "深度研究", "自动化工作台", "长任务执行"],
  },
  {
    category: "UI Interaction",
    description: "跟随指针移动的卡片高光，让静态卡片产生明确的交互反馈。",
    categoryZh: "界面交互",
    displayNameZh: "卡片高光",
    difficulty: "easy",
    id: "card-highlight",
    mode: "interaction",
    name: "Card Highlight",
    packageAssets: commonAssets(),
    packageStatus: "preview_only",
    problem: "卡片 Hover 经常只改变颜色，缺少能被复制的空间反馈和参数。",
    previewStatus: "preview_ready",
    slug: "card-highlight",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "CSS", "Pointer Events"],
    summary: "让卡片和磁贴跟随指针产生高光反馈。",
    tags: ["Hover", "Card", "Interaction", "Apple"],
    useCases: ["产品卡片", "价格卡", "作品集", "游戏界面"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "跟随鼠标移动的径向光斑和边框反馈，让卡片在不打断阅读的情况下产生空间感。",
    difficulty: "easy",
    displayNameZh: "玻璃光斑卡片",
    id: "magic-card",
    mode: "interaction",
    name: "Magic Card",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "普通 Hover 往往只改变颜色，缺少能被复用的指针位置、光斑和边框反馈。",
    previewStatus: "preview_ready",
    slug: "magic-card",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "CSS", "Pointer Events"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 2, subtitleZh: "把玻璃光斑卡片拆成可复用的交互" },
    summary: "让卡片根据指针位置产生光斑和边框反馈。",
    tags: ["Hover", "Spotlight", "Card", "Interaction", "Glow"],
    useCases: ["AI 产品卡片", "价格卡", "提示词结果", "数据面板"],
  },
  {
    category: "Chat UI",
    categoryZh: "聊天界面",
    description: "把请求等待、文字持续流入、自动滚动和完成状态组织成连续的 AI 回复体验。",
    difficulty: "medium",
    displayNameZh: "流式聊天回复",
    id: "streaming-chat",
    mode: "ai_native",
    name: "Streaming Chat",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 生成完整答案需要时间，如果界面持续空白，用户无法判断请求是否已经响应或还要等待多久。",
    previewStatus: "preview_ready",
    slug: "streaming-chat",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "ARIA Live Regions", "Streaming State"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 3, subtitleZh: "把 AI 回复拆成等待、流入、滚动和完成状态" },
    summary: "让 AI 回复一段一段出现，并持续给出清楚的生成反馈。",
    tags: ["Streaming", "Chat UI", "AI Reply", "Auto Scroll", "Loading"],
    useCases: ["AI 对话", "内容生成", "知识问答", "Agent 工作台"],
  },
  {
    category: "Motion & Animation",
    categoryZh: "动效与动画",
    description: "连接两个界面节点的流动光束，把数据方向、系统关系和处理状态变成可见反馈。",
    difficulty: "medium",
    displayNameZh: "连接光束",
    id: "connection-beam",
    mode: "visual",
    name: "Connection Beam",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "工作流和集成图只画静态连线时，很难表达数据正在向哪里流动以及当前系统关系。",
    previewStatus: "preview_ready",
    slug: "connection-beam",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "SVG", "ResizeObserver"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 4, subtitleZh: "把数据流动变成看得见的连接关系" },
    summary: "让光束沿节点之间的曲线路径持续流动。",
    tags: ["Beam", "Connection", "Workflow", "Agent", "SVG"],
    useCases: ["AI 工作流", "Agent 编排", "上传处理", "产品集成图"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "用快捷键唤起的全局操作入口，支持即时过滤、结果分组、键盘选择和执行反馈。",
    difficulty: "medium",
    displayNameZh: "命令面板",
    id: "command-palette",
    mode: "frontend",
    name: "Command Palette",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "功能较多的 AI 产品容易把操作散落在多层导航中，用户很难快速找到下一步。",
    previewStatus: "preview_ready",
    slug: "command-palette",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Keyboard Events"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 5, subtitleZh: "把搜索、跳转和操作收进同一个入口" },
    summary: "一个同时支持鼠标和键盘操作的全局命令入口。",
    tags: ["Command", "Search", "Keyboard", "快捷键", "Productivity"],
    useCases: ["AI 工具", "后台系统", "编辑器", "知识产品"],
  },
  {
    category: "Image & Media",
    categoryZh: "图片与媒体",
    description: "把文件选择、格式校验、拖入反馈、处理进度和完成结果组织成一套连续输入体验。",
    difficulty: "medium",
    displayNameZh: "智能文件上传区",
    id: "file-upload-dropzone",
    mode: "frontend",
    name: "File Upload Dropzone",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 产品经常需要图片、文档或音频输入，普通上传框无法持续说明文件是否可用、处理到哪一步以及是否完成。",
    previewStatus: "preview_ready",
    slug: "file-upload-dropzone",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "File API", "Drag and Drop API"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 6, subtitleZh: "一个上传框，为什么要设计四种状态" },
    summary: "一个支持拖拽、点击、键盘、校验和进度反馈的文件输入区。",
    tags: ["Upload", "Dropzone", "File", "Image Upload", "AI Input"],
    useCases: ["图片生成", "文档分析", "音频转写", "知识库导入"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "让列表项目在拖动过程中提前让出位置，并提供按钮与键盘完成同一套排序。",
    difficulty: "medium",
    displayNameZh: "拖拽排序列表",
    id: "sortable-list",
    mode: "interaction",
    name: "Sortable List",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "AI 工作流、任务队列和提示词步骤经常需要调整顺序，但普通拖拽容易让落点不清楚，也缺少触屏和键盘替代操作。",
    previewStatus: "preview_ready",
    slug: "sortable-list",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Pointer Events"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 7, subtitleZh: "拖动一张卡片，为什么其他卡片会自动让位" },
    summary: "一个支持指针拖动、上下按钮和键盘操作的列表重排组件。",
    tags: ["Sortable", "Drag", "Drop", "List", "Keyboard"],
    useCases: ["提示词步骤", "AI 工作流", "任务优先级", "素材队列"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "用接近最终内容结构的占位骨架承接等待过程，并在内容出现时保持布局稳定。",
    difficulty: "easy",
    displayNameZh: "骨架屏加载",
    id: "skeleton-loader",
    mode: "frontend",
    name: "Skeleton Loader",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "空白等待和旋转图标无法说明页面将出现什么，也容易在内容载入后造成明显跳动。",
    previewStatus: "preview_ready",
    slug: "skeleton-loader",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "CSS"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 8, subtitleZh: "骨架屏为什么比转圈更让人安心" },
    summary: "一个支持结构占位、加载状态语义和减少动画偏好的内容骨架。",
    tags: ["Skeleton", "Loading", "Shimmer", "Layout", "Accessibility"],
    useCases: ["AI 回答历史", "项目列表", "数据面板", "内容详情"],
  },
  {
    category: "Chat UI",
    categoryZh: "聊天界面",
    description: "把自动增高、附件、发送快捷键和生成中状态组织成一个可复用的 AI 输入模块。",
    difficulty: "medium",
    displayNameZh: "智能聊天输入框",
    id: "prompt-composer",
    mode: "ai_native",
    name: "Prompt Composer",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "普通输入框无法同时处理长提示词、附件、中文输入法、快捷发送和生成中的停止操作。",
    previewStatus: "preview_ready",
    slug: "prompt-composer",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Textarea API", "Keyboard Events"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 9, subtitleZh: "一个聊天输入框为什么要处理这么多状态" },
    summary: "一个支持长文本、附件、快捷键和发送/停止状态的 AI 输入框。",
    tags: ["Chat Input", "Prompt", "Textarea", "Attachment", "AI"],
    useCases: ["AI 对话", "内容生成", "Agent 指令", "文档问答"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "在完整导航、图标导航和移动端抽屉之间切换，保留当前页面和键盘操作语义。",
    difficulty: "medium",
    displayNameZh: "可折叠侧边栏",
    id: "collapsible-sidebar",
    mode: "interaction",
    name: "Collapsible Sidebar",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "功能较多的 AI 产品需要长期导航，但固定宽侧栏会挤压编辑区，移动端还需要完全不同的展开方式。",
    previewStatus: "preview_ready",
    slug: "collapsible-sidebar",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "CSS Media Queries", "ARIA"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 10, subtitleZh: "侧边栏收起来以后，哪些信息必须留下" },
    summary: "一个支持桌面收起、图标提示和移动端抽屉的响应式导航侧栏。",
    tags: ["Sidebar", "Navigation", "Responsive", "Disclosure", "Dashboard"],
    useCases: ["AI 工作台", "管理后台", "编辑器", "知识库"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "把多条状态反馈组织成可展开的通知队列，并在新增或关闭时连续补位。",
    difficulty: "medium",
    displayNameZh: "堆叠通知",
    id: "toast-stack",
    mode: "interaction",
    name: "Toast Stack",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "保存、生成和上传等状态会同时出现；普通提示容易互相遮挡、跳动或阻塞内容。",
    previewStatus: "preview_ready",
    slug: "toast-stack",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "CSS", "ARIA Live Regions"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 11, subtitleZh: "为什么通知会自动给下一条让位" },
    summary: "一个支持堆叠、展开、关闭和连续补位的状态通知队列。",
    tags: ["Toast", "Notification", "Stack", "Feedback", "Status"],
    useCases: ["保存反馈", "生成完成", "上传结果", "后台任务"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "把任意本地图片放进可拖拽角色容器，补上边界限制、待机呼吸和键盘移动。",
    difficulty: "medium",
    displayNameZh: "图片桌宠",
    id: "image-desktop-pet",
    mode: "interaction",
    name: "Image Desktop Pet",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "一张角色图片放进产品后仍然是静态素材；拖拽、边界、待机动作和桌面窗口职责经常混在一起。",
    previewStatus: "preview_ready",
    slug: "image-desktop-pet",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Pointer Events", "File API"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 12, subtitleZh: "一张普通图片怎样变成会动的桌宠" },
    summary: "一个支持本地换图、拖拽、边界限制和待机呼吸的图片桌宠。",
    tags: ["Desktop Pet", "Drag", "Image", "Pointer Events", "Avatar"],
    useCases: ["桌面角色", "网页悬浮助手", "互动头像", "陪伴式工具"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "选中文字后在选区附近显示上下文操作，并处理定位、边界和选区保留。",
    difficulty: "medium",
    displayNameZh: "文本选区工具栏",
    id: "text-selection-toolbar",
    mode: "interaction",
    name: "Text Selection Toolbar",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "固定工具栏会长期占据编辑空间；普通浮层又容易遮挡文字、越过边界或在点击时丢失选区。",
    previewStatus: "preview_ready",
    slug: "text-selection-toolbar",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Selection API", "Range API"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 13, subtitleZh: "选中文字后，工具栏怎样跟住选区" },
    summary: "一个只在需要时出现、会跟随选区并保留原文字选择的上下文工具栏。",
    tags: ["Toolbar", "Selection", "Editor", "Floating UI", "AI Writing"],
    useCases: ["AI 写作", "翻译编辑", "知识库", "富文本编辑器"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "让新主题从用户点击的位置以圆形扩张，并覆盖到容器最远角。",
    difficulty: "medium",
    displayNameZh: "圆形主题切换",
    id: "circular-theme-reveal",
    mode: "interaction",
    name: "Circular Theme Reveal",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "直接替换深浅主题会产生突然跳变，用户难以把点击动作和页面变化联系起来。",
    previewStatus: "preview_ready",
    slug: "circular-theme-reveal",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Web Animations API", "Clip Path"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 14, subtitleZh: "点一下以后，整页为什么从这里变暗" },
    summary: "一个从点击位置开始、完整覆盖容器并适配减少动画的主题切换。",
    tags: ["Theme", "Dark Mode", "Reveal", "Clip Path", "Motion"],
    useCases: ["AI 工作台", "SaaS 控制台", "开发者工具", "内容平台"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "让一张卡片从原位置连续扩张为详情弹窗，关闭时沿相同路径返回。",
    difficulty: "medium",
    displayNameZh: "卡片变形弹窗",
    id: "morphing-dialog",
    mode: "interaction",
    name: "Morphing Dialog",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    problem: "普通弹窗突然出现时，用户需要重新寻找内容，也无法感知详情与原卡片之间的关系。",
    previewStatus: "preview_ready",
    slug: "morphing-dialog",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "TypeScript", "Portal", "Focus Management"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 15, subtitleZh: "卡片为什么能连续变成一个弹窗" },
    summary: "一个保留视觉对应关系、焦点管理和关闭路径的卡片详情弹窗。",
    tags: ["Dialog", "Card", "Morph", "Modal", "Shared Element"],
    useCases: ["AI 模型详情", "Agent 卡片", "生成结果", "模板预览"],
  },
  {
    category: "UI Interaction",
    description: "可复用的双面翻卡结构，支持前后内容和揭示状态。",
    categoryZh: "界面交互",
    displayNameZh: "双面翻卡",
    difficulty: "easy",
    id: "flip-card",
    mode: "interaction",
    name: "Flip Card",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "前后内容切换需要同时处理可访问性、触摸和动画状态。",
    previewStatus: "planned",
    slug: "flip-card",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "一套可复用的双面内容揭示交互。",
    tags: ["Card", "Flip", "Reveal", "Game UI"],
    useCases: ["抽卡", "学习卡片", "产品介绍", "奖励展示"],
  },
  {
    category: "Motion & Animation",
    description: "照片散落、聚合和重排的动效，用于相册和视觉墙。",
    categoryZh: "动效与动画",
    displayNameZh: "照片散落动画",
    difficulty: "medium",
    id: "photo-scatter",
    mode: "visual",
    name: "Photo Scatter",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "图片墙需要有节奏的空间变化，但手写动画难以复用。",
    previewStatus: "planned",
    slug: "photo-scatter",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "让照片集合完成散落、聚合和重新排列。",
    tags: ["Gallery", "Motion", "Photo", "Animation"],
    useCases: ["相册", "作品集", "分享页", "落地页"],
  },
  {
    category: "Motion & Animation",
    description: "抽卡、翻牌和结果揭示组成的奖励反馈模块。",
    categoryZh: "动效与动画",
    displayNameZh: "抽卡揭示动画",
    difficulty: "medium",
    id: "draw-card-animation",
    mode: "interaction",
    name: "Draw Card Animation",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "抽卡反馈往往依赖一整套状态机，难以从单个动画复制到产品。",
    previewStatus: "planned",
    slug: "draw-card-animation",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "用于抽卡、奖励和游戏结果的揭示动画。",
    tags: ["Game UI", "Draw", "Reward", "Reveal"],
    useCases: ["游戏奖励", "签到反馈", "抽奖", "结果页"],
  },
  {
    category: "Image & Vision",
    description: "支持比例锁定、拖动和导出的图片裁剪能力。",
    categoryZh: "图片与视觉",
    displayNameZh: "图片裁剪器",
    difficulty: "medium",
    id: "image-cropper",
    mode: "frontend",
    name: "Image Cropper",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "图片上传流程经常需要裁剪、比例和导出，却重复实现同一套交互。",
    previewStatus: "planned",
    slug: "image-cropper",
    sourceStatus: "planned",
    stack: ["React", "Canvas", "TypeScript"],
    summary: "一套专注于裁剪、比例和导出的图片流程。",
    tags: ["Image", "Crop", "Upload", "Canvas"],
    useCases: ["头像上传", "内容编辑", "分享海报", "图片工具"],
  },
  {
    category: "UI Interaction",
    description: "图片选择、预览、排序和确认的一套相册输入流程。",
    categoryZh: "界面交互",
    displayNameZh: "相册选择器",
    difficulty: "medium",
    id: "album-picker",
    mode: "frontend",
    name: "Album Picker",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "多图输入需要同时处理选择、排序、删除和确认状态。",
    previewStatus: "planned",
    slug: "album-picker",
    sourceStatus: "planned",
    stack: ["React", "TypeScript", "CSS"],
    summary: "适合创意工具的多图片选择流程。",
    tags: ["Album", "Picker", "Upload", "Gallery"],
    useCases: ["AI 图片工具", "相册", "内容编辑", "作品集"],
  },
  {
    category: "Visual Effects",
    description: "根据图片或色板生成可调节的渐变背景。",
    categoryZh: "视觉效果",
    displayNameZh: "渐变背景",
    difficulty: "easy",
    id: "gradient-background",
    mode: "visual",
    name: "Gradient Background",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "渐变背景常被当作一次性视觉，而不是可复用的主题输入。",
    previewStatus: "planned",
    slug: "gradient-background",
    sourceStatus: "planned",
    stack: ["CSS", "React", "Color Tokens"],
    summary: "一套可以调节参数的产品渐变背景。",
    tags: ["Gradient", "Background", "Theme", "Visual"],
    useCases: ["Hero", "卡片", "主题系统", "分享海报"],
  },
  {
    category: "Image & Media",
    description: "把图片和色板组合成可分享的票根或结果海报。",
    categoryZh: "图片与媒体",
    displayNameZh: "票根分享海报",
    difficulty: "medium",
    id: "ticket-share-poster",
    mode: "frontend",
    name: "Ticket Share Poster",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "分享结果需要统一布局、导出和移动端可读性。",
    previewStatus: "planned",
    slug: "ticket-share-poster",
    sourceStatus: "planned",
    stack: ["React", "Canvas", "CSS"],
    summary: "把结果生成适合分享的票根风格海报。",
    tags: ["Share", "Poster", "Canvas", "Social"],
    useCases: ["结果分享", "邀请卡", "勋章", "活动页"],
  },
  {
    category: "Map & Data",
    description: "自定义 Marker、选中态和信息卡的地图交互接口。",
    categoryZh: "地图与数据",
    displayNameZh: "地图标记交互",
    difficulty: "advanced",
    id: "map-marker",
    mode: "frontend",
    name: "Map Marker",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    problem: "地图 Marker 同时涉及状态、聚类和信息卡，常常被锁在单个项目里。",
    previewStatus: "planned",
    slug: "map-marker",
    sourceStatus: "planned",
    stack: ["React", "Map SDK", "TypeScript"],
    summary: "一套可复用的地图标记和选中状态交互。",
    tags: ["Map", "Marker", "Data", "Location"],
    useCases: ["地图产品", "地点收藏", "门店", "数据可视化"],
  },
];

export function getCapabilities(query?: string): Capability[] {
  const normalized = query?.trim().toLocaleLowerCase();
  if (!normalized) return capabilities;
  return capabilities.filter((capability) =>
    [
      capability.name,
      capability.displayNameZh ?? "",
      capability.summary,
      capability.description,
      capability.category,
      getCategoryLabel(capability.category),
      ...capability.tags,
      ...capability.stack,
      ...capability.useCases,
      capability.mode === "ai_native" ? "AI" : "",
      capability.packageAssets.some((asset) => asset.label.includes("Prompt") || asset.label.includes("提示词")) ? "Prompt 提示词" : "",
      capability.useCases.some((useCase) => useCase.toLocaleLowerCase().includes("hero")) ? "Landing Page" : "",
      capability.stack.includes("React") ? "Developer Tool" : "",
    ].some((value) => value.toLocaleLowerCase().includes(normalized)),
  );
}

export function getCapabilityBySlug(slug: string) {
  return capabilities.find((capability) => capability.slug === slug) ?? null;
}

export function getCapabilityAccessLabel(capability: Capability) {
  return capability.packageStatus === "ready_for_checkout" ? "免费开放" : "准备中";
}

export function getCapabilityCategories() {
  return [...new Set(capabilities.map(({ category }) => category))];
}

export function getCapabilityStacks() {
  return [...new Set(capabilities.flatMap(({ stack }) => stack))].sort();
}
