import type { Capability } from "./types";

const commonAssets = (ready: string[] = []): Capability["packageAssets"] => {
  const assets = [
    ["Self-owned source", "源码"],
    ["Cursor Prompt", "Cursor Prompt"],
    ["Claude Prompt", "Claude Prompt"],
    ["README", "README"],
    ["Parameters", "参数说明"],
    ["Integration Guide", "Integration Guide"],
    ["License", "License"],
  ] as const;
  return assets.map(([key, label]) => ({
    label,
    status: ready.includes(key) ? "ready" : "planned",
    note: ready.includes(key) ? "已在本地预览中验证" : "尚未作为公开 Package 交付",
  }));
};

export const capabilities: Capability[] = [
  {
    category: "Image & Vision",
    description: "从图片提取主色、辅助色和可复用的调色板结果。",
    difficulty: "medium",
    id: "image-color-extractor",
    mode: "ai_native",
    name: "Color Extraction",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    priceDisplay: "$9 · mock price",
    problem: "图片里的颜色很难快速转成可用于 UI、海报或主题系统的结构化数据。",
    previewStatus: "preview_ready",
    slug: "color-extraction",
    sourceStatus: "self_owned_prototype",
    stack: ["Canvas", "React", "TypeScript"],
    summary: "Turn any image into a usable color palette.",
    tags: ["Color Picker", "Palette", "Vision", "Image"],
    useCases: ["主题色生成", "图片分析", "视觉灵感板", "分享海报"],
  },
  {
    category: "Visual Effects",
    categoryZh: "视觉效果",
    description: "可复用的玻璃拟态卡片，支持模糊、透明度、边框、高光和鼠标交互。",
    displayNameZh: "玻璃拟态卡片",
    difficulty: "easy",
    id: "glass-surface",
    mode: "visual",
    name: "Glass Surface",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    priceDisplay: "¥4 · mock price",
    problem: "玻璃拟态容易停留在视觉模仿，难以形成可复用的参数和接入方式。",
    previewStatus: "preview_ready",
    slug: "glass-surface",
    sourceStatus: "self_owned_prototype",
    stack: ["CSS", "React", "Tailwind"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 1, subtitleZh: "拆解 AI 产品里最常见的 Glass Card 效果" },
    summary: "一张可以直接接入 AI 产品的玻璃拟态卡片。",
    tags: ["Glass", "VisionOS", "Apple", "Surface"],
    useCases: ["AI 数据面板", "首页首屏", "结果卡片", "媒体预览"],
  },
  {
    category: "UI Interaction",
    description: "跟随指针移动的卡片高光，让静态卡片产生明确的交互反馈。",
    difficulty: "easy",
    id: "card-highlight",
    mode: "interaction",
    name: "Card Highlight",
    packageAssets: commonAssets(),
    packageStatus: "preview_only",
    priceDisplay: "$4 · mock price",
    problem: "卡片 Hover 经常只改变颜色，缺少能被复制的空间反馈和参数。",
    previewStatus: "preview_ready",
    slug: "card-highlight",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "CSS", "Pointer Events"],
    summary: "A pointer-aware highlight layer for cards and tiles.",
    tags: ["Hover", "Card", "Interaction", "Apple"],
    useCases: ["产品卡片", "价格卡", "作品集", "游戏 UI"],
  },
  {
    category: "UI Interaction",
    categoryZh: "界面交互",
    description: "跟随鼠标移动的径向光斑和边框反馈，让卡片在不打断阅读的情况下产生空间感。",
    difficulty: "easy",
    displayNameZh: "玻璃光斑卡片",
    id: "magic-card",
    mode: "interaction",
    name: "Magic Card",
    packageAssets: commonAssets(["Self-owned source", "Cursor Prompt", "Claude Prompt", "README", "Parameters", "Integration Guide", "License"]),
    packageStatus: "ready_for_checkout",
    priceDisplay: "¥4 · mock price",
    problem: "普通 Hover 往往只改变颜色，缺少能被复用的指针位置、光斑和边框反馈。",
    previewStatus: "preview_ready",
    slug: "magic-card",
    sourceStatus: "self_owned_prototype",
    stack: ["React", "CSS", "Pointer Events"],
    series: { nameZh: "每天拆一个 AI 产品", episode: 2, subtitleZh: "把 Magic Card 拆成可复用的光斑交互" },
    summary: "一张会对鼠标位置做出反馈的光斑卡片。",
    tags: ["Hover", "Spotlight", "Card", "Interaction", "Glow"],
    useCases: ["AI 产品卡片", "Pricing Card", "Prompt 结果", "Dashboard"],
  },
  {
    category: "UI Interaction",
    description: "可复用的双面翻卡结构，支持前后内容和揭示状态。",
    difficulty: "easy",
    id: "flip-card",
    mode: "interaction",
    name: "Flip Card",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$4 · mock price",
    problem: "前后内容切换需要同时处理可访问性、触摸和动画状态。",
    previewStatus: "planned",
    slug: "flip-card",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "A reusable two-sided card reveal interaction.",
    tags: ["Card", "Flip", "Reveal", "Game UI"],
    useCases: ["抽卡", "学习卡片", "产品介绍", "奖励展示"],
  },
  {
    category: "Motion & Animation",
    description: "照片散落、聚合和重排的动效，用于相册和视觉墙。",
    difficulty: "medium",
    id: "photo-scatter",
    mode: "visual",
    name: "Photo Scatter",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$9 · mock price",
    problem: "图片墙需要有节奏的空间变化，但手写动画难以复用。",
    previewStatus: "planned",
    slug: "photo-scatter",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "Scatter, gather and rearrange a photo collection.",
    tags: ["Gallery", "Motion", "Photo", "Animation"],
    useCases: ["相册", "作品集", "分享页", "Landing Page"],
  },
  {
    category: "Motion & Animation",
    description: "抽卡、翻牌和结果揭示组成的奖励反馈模块。",
    difficulty: "medium",
    id: "draw-card-animation",
    mode: "interaction",
    name: "Draw Card Animation",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$9 · mock price",
    problem: "抽卡反馈往往依赖一整套状态机，难以从单个动画复制到产品。",
    previewStatus: "planned",
    slug: "draw-card-animation",
    sourceStatus: "planned",
    stack: ["React", "CSS", "Framer Motion"],
    summary: "A reveal loop for draws, rewards and game results.",
    tags: ["Game UI", "Draw", "Reward", "Reveal"],
    useCases: ["游戏奖励", "签到反馈", "抽奖", "结果页"],
  },
  {
    category: "Image & Vision",
    description: "支持比例锁定、拖动和导出的图片裁剪能力。",
    difficulty: "medium",
    id: "image-cropper",
    mode: "frontend",
    name: "Image Cropper",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$9 · mock price",
    problem: "图片上传流程经常需要裁剪、比例和导出，却重复实现同一套交互。",
    previewStatus: "planned",
    slug: "image-cropper",
    sourceStatus: "planned",
    stack: ["React", "Canvas", "TypeScript"],
    summary: "A focused crop, ratio and export workflow.",
    tags: ["Image", "Crop", "Upload", "Canvas"],
    useCases: ["头像上传", "内容编辑", "分享海报", "图片工具"],
  },
  {
    category: "UI Interaction",
    description: "图片选择、预览、排序和确认的一套相册输入流程。",
    difficulty: "medium",
    id: "album-picker",
    mode: "frontend",
    name: "Album Picker",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$9 · mock price",
    problem: "多图输入需要同时处理选择、排序、删除和确认状态。",
    previewStatus: "planned",
    slug: "album-picker",
    sourceStatus: "planned",
    stack: ["React", "TypeScript", "CSS"],
    summary: "A compact multi-image picker for creative tools.",
    tags: ["Album", "Picker", "Upload", "Gallery"],
    useCases: ["AI 图片工具", "相册", "内容编辑", "作品集"],
  },
  {
    category: "Visual Effects",
    description: "根据图片或色板生成可调节的渐变背景。",
    difficulty: "easy",
    id: "gradient-background",
    mode: "visual",
    name: "Gradient Background",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$4 · mock price",
    problem: "渐变背景常被当作一次性视觉，而不是可复用的主题输入。",
    previewStatus: "planned",
    slug: "gradient-background",
    sourceStatus: "planned",
    stack: ["CSS", "React", "Color Tokens"],
    summary: "A parameterized gradient system for product surfaces.",
    tags: ["Gradient", "Background", "Theme", "Visual"],
    useCases: ["Hero", "卡片", "主题系统", "分享海报"],
  },
  {
    category: "Image & Media",
    description: "把图片和色板组合成可分享的票根或结果海报。",
    difficulty: "medium",
    id: "ticket-share-poster",
    mode: "frontend",
    name: "Ticket Share Poster",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$9 · mock price",
    problem: "分享结果需要统一布局、导出和移动端可读性。",
    previewStatus: "planned",
    slug: "ticket-share-poster",
    sourceStatus: "planned",
    stack: ["React", "Canvas", "CSS"],
    summary: "Generate a shareable ticket-style result poster.",
    tags: ["Share", "Poster", "Canvas", "Social"],
    useCases: ["结果分享", "邀请卡", "勋章", "活动页"],
  },
  {
    category: "Map & Data",
    description: "自定义 Marker、选中态和信息卡的地图交互接口。",
    difficulty: "advanced",
    id: "map-marker",
    mode: "frontend",
    name: "Map Marker",
    packageAssets: commonAssets(),
    packageStatus: "planned",
    priceDisplay: "$19 · mock price",
    problem: "地图 Marker 同时涉及状态、聚类和信息卡，常常被锁在单个项目里。",
    previewStatus: "planned",
    slug: "map-marker",
    sourceStatus: "planned",
    stack: ["React", "Map SDK", "TypeScript"],
    summary: "A reusable marker and selected-state interaction.",
    tags: ["Map", "Marker", "Data", "Location"],
    useCases: ["地图产品", "地点收藏", "门店", "数据可视化"],
  },
];

export function getCapabilities(query?: string): Capability[] {
  const normalized = query?.trim().toLocaleLowerCase();
  if (!normalized) return capabilities;
  return capabilities.filter((capability) =>
    [
      capability.name,
      capability.displayNameZh ?? "",
      capability.summary,
      capability.description,
      capability.category,
      ...capability.tags,
      ...capability.stack,
      ...capability.useCases,
      capability.mode === "ai_native" ? "AI" : "",
      capability.packageAssets.some((asset) => asset.label.includes("Prompt")) ? "Prompt" : "",
      capability.useCases.some((useCase) => useCase.toLocaleLowerCase().includes("hero")) ? "Landing Page" : "",
      capability.stack.includes("React") ? "Developer Tool" : "",
    ].some((value) => value.toLocaleLowerCase().includes(normalized)),
  );
}

export function getCapabilityBySlug(slug: string) {
  return capabilities.find((capability) => capability.slug === slug) ?? null;
}

export function getCapabilityCategories() {
  return [...new Set(capabilities.map(({ category }) => category))];
}

export function getCapabilityStacks() {
  return [...new Set(capabilities.flatMap(({ stack }) => stack))].sort();
}
